# Welcome to Jekyll!

# Site settings
title: "Jalpc"

baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Jack'
  first_name: 'Jia'
  last_name: 'Kun'
  email: 'jack19890614@gmail.com'
  facebook_username: 'jiakunnj'
  github_username: 'Jack614'
  head_img: 'static/img/landing/Jack.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  blog: 'Blog'
  contact: 'Contact'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  appid: cysfY7ULn
  conf: prod_861928934cecb7a18e15bedaed9dae29

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge