# Welcome to Jekyll!

# Website settings
title: "AmJ"
description: "Personal page using Jack's JalPC Jekyll theme"
keywords: "Ashutosh,AmJ,Profile, Blog,Jekyll,github,gh-page"
baseurl: "/"
 url: "https://ashutoshmjain.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'AmJ'
  first_name: 'Ashutosh'
  last_name: 'Jain'
  email: 'amj@smbstack.com'
  facebook_username: 'ashutoshmjain'
  github_username: 'ashutoshmjain'
  twitter_username: 'ashutoshmjain'
  avatar: 'static/img/landing/profilepic.png'
  desc: 'I am a solution architect and project manager in enterprise apps such as ERP, CRM, SCM, Finance. I am  free and open source enthusiast and regular blogger. Life is a continuous learning process, so work makes me more rigorous.'
# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: 'ashutoshmjain'
  #public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
        #uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
        #id: UA-73784599-1

# growingIO
gio:
        #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
