# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack's blog

baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

author:
  name: 'Jack'
  email: 'jack19890614@gmail.com'
  # twitter_username: joshgerdes
  facebook_username: jiakunnj
  github_username: 'Jack614'
  # linkedin_username:  joshgerdes

# Build settings
markdown: kramdown
highlighter: rouge
encoding: "utf-8"
